import type { Recipe } from "./types"

export const dummyJapchaeRecipes: Recipe[] = [
  {
    id: "1",
    name: "전통 잡채",
    thumbnail: "/korean-japchae-glass-noodles-colorful-vegetables.jpg",
    tags: ["명절", "전통", "파티요리"],
    hashtags: ["백종원", "집밥백선생"],
    duration: 40,
    difficulty: "중급",
    servings: 4,
    calories: 380,
    description: "명절에 빠지지 않는 전통 잡채! 당면과 다양한 채소, 소고기가 어우러진 한국의 대표 명절 음식입니다.",
    nutrition: {
      protein: 12,
      carbs: 58,
      fat: 14,
      fiber: 4,
      sodium: 680,
      sugar: 8,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "당면 불리기",
        description: "당면을 미지근한 물에 30분간 불립니다.",
        ingredients: ["당면 200g"],
        tools: ["큰 볼"],
        duration: 180,
        imageUrl: "/glass-noodles-soaking-in-water.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "채소 썰기",
        description: "당근, 양파, 시금치, 표고버섯을 채 썹니다.",
        ingredients: ["당근 1개", "양파 1개", "시금치 100g", "표고버섯 4개"],
        tools: ["도마", "칼"],
        duration: 300,
        imageUrl: "/sliced-vegetables-carrots-onions-for-cooking.jpg",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "채소 볶기",
        description: "각 채소를 따로 볶아 접시에 담아둡니다.",
        ingredients: ["식용유 2T", "소금 약간"],
        tools: ["프라이팬", "뒤집개"],
        duration: 600,
        imageUrl: "/stir-frying-vegetables-in-pan.jpg",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "소고기 볶기",
        description: "소고기를 양념하여 볶습니다.",
        ingredients: ["소고기 150g", "간장 1T", "설탕 0.5T", "참기름 1T"],
        tools: ["프라이팬"],
        duration: 300,
        imageUrl: "/cooking-beef-strips-in-pan.jpg",
        tips: "고기는 센 불에서 빠르게 볶아야 질기지 않아요",
      },
      {
        id: 5,
        stepNumber: 5,
        action: "당면 삶기",
        description: "불린 당면을 끓는 물에 5분간 삶아 찬물에 헹굽니다.",
        ingredients: ["불린 당면"],
        tools: ["냄비", "체"],
        duration: 360,
        imageUrl: "/boiling-glass-noodles-in-pot.jpg",
      },
      {
        id: 6,
        stepNumber: 6,
        action: "양념장 만들기",
        description: "간장, 설탕, 참기름을 섞어 양념장을 만듭니다.",
        ingredients: ["간장 3T", "설탕 1.5T", "참기름 2T", "다진 마늘 1T"],
        tools: ["작은 볼"],
        duration: 60,
        imageUrl: "/korean-sauce-soy-sauce-sesame-oil.jpg",
      },
      {
        id: 7,
        stepNumber: 7,
        action: "모두 섞기",
        description: "큰 볼에 당면과 모든 재료를 넣고 양념장과 함께 버무립니다.",
        ingredients: ["통깨 약간"],
        tools: ["큰 볼", "젓가락"],
        duration: 180,
        imageUrl: "/mixing-japchae-all-ingredients-together-colorful.jpg",
      },
    ],
  },
  {
    id: "2",
    name: "10분 초간단 잡채",
    thumbnail: "/quick-easy-japchae-simple-cooking.jpg",
    tags: ["초보", "10분", "간편식"],
    hashtags: ["승수아빠", "요리뚝딱"],
    duration: 10,
    difficulty: "초보",
    servings: 2,
    calories: 320,
    description: "바쁜 일상 속에서도 간편하게 만들 수 있는 10분 초스피드 잡채 레시피입니다.",
    nutrition: {
      protein: 8,
      carbs: 52,
      fat: 10,
      fiber: 3,
      sodium: 520,
      sugar: 6,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "재료 준비",
        description: "미리 삶아둔 당면과 냉동 야채를 준비합니다.",
        ingredients: ["즉석 당면 150g", "냉동 야채믹스 1컵"],
        tools: ["프라이팬"],
        duration: 60,
        imageUrl: "/pre-cooked-glass-noodles-frozen-vegetables.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "볶기",
        description: "모든 재료를 한 번에 볶습니다.",
        ingredients: ["간장 2T", "참기름 1T", "설탕 0.5T"],
        tools: ["프라이팬", "뒤집개"],
        duration: 300,
        imageUrl: "/quick-stir-fry-noodles-vegetables.jpg",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "마무리",
        description: "통깨를 뿌려 완성합니다.",
        ingredients: ["통깨"],
        tools: [],
        duration: 30,
        imageUrl: "/finished-japchae-with-sesame-seeds.jpg",
      },
    ],
  },
  {
    id: "3",
    name: "매콤 불잡채",
    thumbnail: "/spicy-korean-japchae-with-red-pepper.jpg",
    tags: ["매콤", "술안주", "인기"],
    hashtags: ["만개의레시피", "술안주맛집"],
    duration: 35,
    difficulty: "중급",
    servings: 3,
    calories: 410,
    description: "매콤한 양념이 입맛을 돋우는 불잡채! 술안주로도 밥반찬으로도 최고예요.",
    nutrition: {
      protein: 14,
      carbs: 55,
      fat: 16,
      fiber: 5,
      sodium: 780,
      sugar: 10,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "당면 불리기",
        description: "당면을 30분간 불립니다.",
        ingredients: ["당면 200g"],
        tools: ["볼"],
        duration: 180,
        imageUrl: "/glass-noodles-soaking-water-bowl.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "양념장 만들기",
        description: "고추장, 고춧가루, 간장을 섞어 매운 양념장을 만듭니다.",
        ingredients: ["고추장 2T", "고춧가루 1T", "간장 2T", "설탕 1T"],
        tools: ["작은 볼"],
        duration: 60,
        imageUrl: "/korean-spicy-sauce-gochujang-mixing.jpg",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "채소와 고기 볶기",
        description: "센 불에서 재료를 볶습니다.",
        ingredients: ["소고기 100g", "양파 1개", "청양고추 2개"],
        tools: ["프라이팬"],
        duration: 420,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "당면 넣고 볶기",
        description: "삶은 당면을 넣고 양념장과 함께 볶습니다.",
        ingredients: ["삶은 당면"],
        tools: ["프라이팬"],
        duration: 240,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 5,
        stepNumber: 5,
        action: "마무리",
        description: "참기름과 깨를 뿌려 완성합니다.",
        ingredients: ["참기름 1T", "통깨"],
        tools: [],
        duration: 30,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
  {
    id: "4",
    name: "해물 잡채",
    thumbnail: "/placeholder.svg?height=300&width=400",
    tags: ["해산물", "고급", "파티요리"],
    hashtags: ["이연복", "목란"],
    duration: 45,
    difficulty: "상급",
    servings: 4,
    calories: 350,
    description: "신선한 해산물이 가득 들어간 고급스러운 해물 잡채입니다.",
    nutrition: {
      protein: 22,
      carbs: 48,
      fat: 12,
      fiber: 3,
      sodium: 850,
      sugar: 5,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "해산물 손질",
        description: "새우, 오징어, 홍합을 깨끗이 손질합니다.",
        ingredients: ["새우 10마리", "오징어 1마리", "홍합 10개"],
        tools: ["도마", "칼"],
        duration: 420,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "당면 준비",
        description: "당면을 불리고 삶습니다.",
        ingredients: ["당면 200g"],
        tools: ["냄비", "볼"],
        duration: 600,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "채소 볶기",
        description: "각종 채소를 볶아둡니다.",
        ingredients: ["양파 1개", "당근 1개", "피망 2개"],
        tools: ["프라이팬"],
        duration: 480,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "해산물 볶기",
        description: "해산물을 센 불에서 빠르게 볶습니다.",
        ingredients: ["손질한 해산물"],
        tools: ["프라이팬"],
        duration: 240,
        imageUrl: "/placeholder.svg?height=400&width=600",
        tips: "해산물은 오래 익히면 질겨져요!",
      },
      {
        id: 5,
        stepNumber: 5,
        action: "모두 섞기",
        description: "당면, 채소, 해산물을 양념과 함께 버무립니다.",
        ingredients: ["간장 3T", "참기름 2T", "굴소스 1T"],
        tools: ["큰 볼"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
  {
    id: "5",
    name: "비건 채소 잡채",
    thumbnail: "/placeholder.svg?height=300&width=400",
    tags: ["비건", "건강식", "다이어트"],
    hashtags: ["비건언니", "건강요리"],
    duration: 30,
    difficulty: "초보",
    servings: 3,
    calories: 280,
    description: "고기 없이도 맛있는 건강한 비건 잡채! 다이어트 중에도 부담없이 즐기세요.",
    nutrition: {
      protein: 6,
      carbs: 52,
      fat: 8,
      fiber: 6,
      sodium: 420,
      sugar: 4,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "당면 불리기",
        description: "당면을 불립니다.",
        ingredients: ["당면 150g"],
        tools: ["볼"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "다양한 채소 준비",
        description: "여러 가지 색색깔 채소를 준비합니다.",
        ingredients: ["시금치 100g", "당근 1개", "표고버섯 4개", "청피망 1개", "홍피망 1개"],
        tools: ["도마", "칼"],
        duration: 300,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "채소 볶기",
        description: "올리브오일로 채소를 볶습니다.",
        ingredients: ["올리브오일 2T", "소금 약간"],
        tools: ["프라이팬"],
        duration: 480,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "비건 양념장",
        description: "코코넛 아미노스로 양념장을 만듭니다.",
        ingredients: ["코코넛 아미노스 3T", "메이플시럽 1T", "참기름 1T"],
        tools: ["작은 볼"],
        duration: 60,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 5,
        stepNumber: 5,
        action: "버무리기",
        description: "모든 재료를 섞어 완성합니다.",
        ingredients: ["통깨"],
        tools: ["큰 볼"],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
]

export const leftoverRecipes: Recipe[] = [
  {
    id: "leftover-1",
    name: "달걀말이",
    thumbnail: "/placeholder.svg?height=100&width=100",
    tags: ["간편", "아침식사"],
    duration: 10,
    difficulty: "초보",
    servings: 2,
    steps: [],
  },
  {
    id: "leftover-2",
    name: "야채 볶음밥",
    thumbnail: "/placeholder.svg?height=100&width=100",
    tags: ["간편", "한끼식사"],
    duration: 15,
    difficulty: "초보",
    servings: 2,
    steps: [],
  },
  {
    id: "leftover-3",
    name: "된장국",
    thumbnail: "/placeholder.svg?height=100&width=100",
    tags: ["국물요리", "건강식"],
    duration: 20,
    difficulty: "초보",
    servings: 4,
    steps: [],
  },
]

export const eggRecipes: Recipe[] = [
  {
    id: "egg-1",
    name: "폭신폭신 계란찜",
    thumbnail: "/korean-steamed-egg-gyeran-jjim.jpg",
    tags: ["간편", "반찬", "부드러움"],
    hashtags: ["백종원", "집밥백선생"],
    duration: 15,
    difficulty: "초보",
    servings: 2,
    calories: 150,
    description: "부드럽고 폭신폭신한 식감의 전통 계란찜. 아이들 반찬으로도 좋고 밥반찬으로도 최고예요.",
    nutrition: {
      protein: 12,
      carbs: 2,
      fat: 10,
      fiber: 0,
      sodium: 380,
      sugar: 1,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "재료 준비",
        description: "계란 3개를 볼에 깨서 넣고 잘 풀어줍니다.",
        ingredients: ["계란 3개", "물 150ml", "소금 0.5t"],
        tools: ["볼", "거품기"],
        duration: 60,
        imageUrl: "/cracking-eggs-into-bowl.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "물과 간 맞추기",
        description: "풀어둔 계란에 물과 소금, 다진 파를 넣고 섞습니다.",
        ingredients: ["다진 파 1T", "참기름 약간"],
        tools: ["볼"],
        duration: 60,
        imageUrl: "/mixing-egg-with-water-and-green-onion.jpg",
        tips: "물 대신 멸치 육수를 넣으면 더 감칠맛이 나요!",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "뚝배기에 담기",
        description: "뚝배기나 내열 용기에 계란물을 붓습니다.",
        ingredients: [],
        tools: ["뚝배기"],
        duration: 30,
        imageUrl: "/pouring-egg-mixture-into-korean-pot.jpg",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "찌기",
        description: "중불에서 뚜껑을 닫고 8-10분간 찌기. 중간에 한 번 저어주면 더 부드러워요.",
        ingredients: [],
        tools: ["뚜껑"],
        duration: 540,
        imageUrl: "/steaming-egg-in-pot-with-lid.jpg",
        tips: "불이 너무 세면 구멍이 많이 생겨요. 중약불로 천천히!",
      },
      {
        id: 5,
        stepNumber: 5,
        action: "마무리",
        description: "참기름을 살짝 뿌리고 깨를 올려 완성합니다.",
        ingredients: ["통깨", "참기름"],
        tools: [],
        duration: 30,
        imageUrl: "/finished-korean-steamed-egg-with-sesame.jpg",
      },
    ],
  },
  {
    id: "egg-2",
    name: "전자레인지 1분 계란찜",
    thumbnail: "/microwave-steamed-egg-quick.jpg",
    tags: ["초간단", "1분", "전자레인지"],
    hashtags: ["요리뚝딱", "자취생필수"],
    duration: 3,
    difficulty: "초보",
    servings: 1,
    calories: 90,
    description: "전자레인지로 1분만에 완성하는 초간단 계란찜! 자취생 필수 레시피.",
    nutrition: {
      protein: 6,
      carbs: 1,
      fat: 5,
      fiber: 0,
      sodium: 200,
      sugar: 0,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "재료 섞기",
        description: "머그컵에 계란 1개와 물 2T를 넣고 잘 섞습니다.",
        ingredients: ["계란 1개", "물 2T", "소금 약간"],
        tools: ["머그컵", "포크"],
        duration: 30,
        imageUrl: "/mixing-egg-in-mug-cup.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "전자레인지 돌리기",
        description: "랩을 씌우고 전자레인지에서 1분 30초 돌립니다.",
        ingredients: [],
        tools: ["전자레인지", "랩"],
        duration: 90,
        imageUrl: "/mug-in-microwave.jpg",
        tips: "전자레인지마다 다르니 처음엔 1분만 돌려보세요!",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "완성",
        description: "꺼내서 파와 참기름을 뿌려 완성!",
        ingredients: ["파", "참기름"],
        tools: [],
        duration: 15,
        imageUrl: "/finished-microwave-steamed-egg.jpg",
      },
    ],
  },
  {
    id: "egg-3",
    name: "부드러운 달걀말이",
    thumbnail: "/korean-rolled-omelette-gyeran-mari.jpg",
    tags: ["반찬", "도시락", "인기"],
    hashtags: ["만개의레시피", "엄마손맛"],
    duration: 15,
    difficulty: "중급",
    servings: 2,
    calories: 180,
    description: "부드럽고 촉촉한 달걀말이. 도시락 반찬으로 인기 만점!",
    nutrition: {
      protein: 14,
      carbs: 3,
      fat: 12,
      fiber: 1,
      sodium: 420,
      sugar: 1,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "계란물 준비",
        description: "계란 4개를 풀고 다진 당근, 파를 넣습니다.",
        ingredients: ["계란 4개", "당근 다진 것 2T", "파 다진 것 2T", "소금 0.5t"],
        tools: ["볼", "거품기"],
        duration: 120,
        imageUrl: "/egg-mixture-with-vegetables.jpg",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "팬 예열",
        description: "약한 불에 팬을 올리고 기름을 두릅니다.",
        ingredients: ["식용유 1T"],
        tools: ["사각팬 또는 프라이팬"],
        duration: 60,
        imageUrl: "/heating-pan-with-oil.jpg",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "계란 붓고 말기",
        description: "계란물을 조금씩 부어 반숙이 되면 한쪽으로 말아줍니다. 3-4회 반복합니다.",
        ingredients: [],
        tools: ["뒤집개"],
        duration: 420,
        imageUrl: "/rolling-korean-egg-omelette.jpg",
        tips: "약한 불에서 천천히 말아야 부드러워요!",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "썰어서 담기",
        description: "완성된 달걀말이를 먹기 좋게 썰어 접시에 담습니다.",
        ingredients: [],
        tools: ["도마", "칼"],
        duration: 60,
        imageUrl: "/sliced-korean-rolled-egg-omelette.jpg",
      },
    ],
  },
]

export function searchRecipes(keyword: string): Recipe[] {
  const allRecipes = [...dummyJapchaeRecipes, ...eggRecipes, ...leftoverRecipes]
  const lowerKeyword = keyword.toLowerCase()

  const matched = allRecipes.filter((recipe) => {
    const nameMatch = recipe.name.toLowerCase().includes(lowerKeyword)
    const tagMatch = recipe.tags.some((tag) => tag.toLowerCase().includes(lowerKeyword))
    const hashtagMatch = recipe.hashtags?.some((tag) => tag.toLowerCase().includes(lowerKeyword))
    return nameMatch || tagMatch || hashtagMatch
  })

  if (matched.length === 0) {
    return allRecipes.slice(0, 5)
  }

  return matched.slice(0, 5)
}

export function getRecipeById(id: string): Recipe | undefined {
  const allRecipes = [...dummyJapchaeRecipes, ...eggRecipes, ...leftoverRecipes]
  return allRecipes.find((recipe) => recipe.id === id)
}

export const allRecipesForBrowse: Recipe[] = [
  {
    id: "browse-1",
    name: "간장 계란밥",
    thumbnail: "/korean-soy-sauce-egg-rice.jpg",
    tags: ["초간단", "자취생", "아침"],
    hashtags: ["백종원"],
    duration: 10,
    difficulty: "초보",
    servings: 1,
    calories: 350,
    description: "간단하지만 맛있는 간장 계란밥! 자취생의 든든한 한 끼.",
    nutrition: {
      protein: 14,
      carbs: 48,
      fat: 12,
      fiber: 1,
      sodium: 580,
      sugar: 3,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "밥 준비",
        description: "따뜻한 밥 한 공기를 그릇에 담습니다.",
        ingredients: ["밥 1공기"],
        tools: ["그릇"],
        duration: 30,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "계란 프라이",
        description: "팬에 기름을 두르고 계란을 반숙으로 프라이합니다.",
        ingredients: ["계란 1개", "식용유 약간"],
        tools: ["프라이팬"],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "양념장 만들기",
        description: "간장, 참기름, 깨를 섞어 양념장을 만듭니다.",
        ingredients: ["간장 1T", "참기름 1t", "통깨"],
        tools: ["작은 그릇"],
        duration: 30,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "완성",
        description: "밥 위에 계란을 올리고 양념장을 뿌려 완성합니다.",
        ingredients: ["김가루 약간"],
        tools: [],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
        tips: "노른자를 터뜨려 밥과 비벼 드세요!",
      },
    ],
  },
  {
    id: "browse-2",
    name: "크림 파스타",
    thumbnail: "/creamy-pasta.png",
    tags: ["브런치", "데이트"],
    hashtags: ["승수아빠"],
    duration: 25,
    difficulty: "중급",
    servings: 2,
    calories: 520,
    description: "부드러운 크림 소스와 파스타의 환상적인 조합.",
    nutrition: {
      protein: 18,
      carbs: 62,
      fat: 24,
      fiber: 3,
      sodium: 720,
      sugar: 4,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "파스타 삶기",
        description: "끓는 물에 소금을 넣고 파스타를 알단테로 삶습니다.",
        ingredients: ["파스타 200g", "물", "소금 1T"],
        tools: ["냄비"],
        duration: 480,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "소스 만들기",
        description: "팬에 버터를 녹이고 마늘을 볶다가 생크림을 넣습니다.",
        ingredients: ["버터 2T", "마늘 3쪽", "생크림 200ml"],
        tools: ["프라이팬"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "파스타와 소스 섞기",
        description: "삶은 파스타를 소스에 넣고 파마산 치즈를 뿌려 섞습니다.",
        ingredients: ["파마산 치즈 3T", "후추"],
        tools: ["집게"],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
        tips: "면수를 조금 넣으면 더 부드러워져요!",
      },
    ],
  },
  {
    id: "browse-3",
    name: "된장찌개",
    thumbnail: "/korean-doenjang-jjigae-stew.jpg",
    tags: ["집밥", "건강식"],
    hashtags: ["요리왕비룡"],
    duration: 30,
    difficulty: "초보",
    servings: 4,
    calories: 180,
    description: "구수한 된장 향이 일품인 전통 된장찌개.",
    nutrition: {
      protein: 10,
      carbs: 18,
      fat: 8,
      fiber: 4,
      sodium: 920,
      sugar: 3,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "육수 준비",
        description: "멸치와 다시마로 육수를 냅니다.",
        ingredients: ["멸치 10마리", "다시마 1장", "물 800ml"],
        tools: ["냄비"],
        duration: 300,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "재료 썰기",
        description: "두부, 감자, 양파, 호박을 먹기 좋게 썹니다.",
        ingredients: ["두부 1/2모", "감자 1개", "양파 1/2개", "애호박 1/2개"],
        tools: ["도마", "칼"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "된장 풀기",
        description: "육수에 된장을 풀고 감자를 먼저 넣어 끓입니다.",
        ingredients: ["된장 2T", "고추장 0.5T"],
        tools: ["국자"],
        duration: 300,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "나머지 재료 넣기",
        description: "감자가 익으면 두부와 호박, 양파를 넣고 끓입니다.",
        ingredients: ["청양고추 1개", "대파 1대"],
        tools: [],
        duration: 300,
        imageUrl: "/placeholder.svg?height=400&width=600",
        tips: "청양고추를 넣으면 칼칼해져요!",
      },
    ],
  },
  {
    id: "browse-4",
    name: "김치볶음밥",
    thumbnail: "/korean-kimchi-fried-rice.jpg",
    tags: ["간편식", "인기"],
    hashtags: ["쿠킹클래스"],
    duration: 15,
    difficulty: "초보",
    servings: 2,
    calories: 420,
    description: "신김치로 만드는 고소한 김치볶음밥. 계란 프라이는 필수!",
    nutrition: {
      protein: 12,
      carbs: 65,
      fat: 14,
      fiber: 3,
      sodium: 680,
      sugar: 5,
    },
    steps: [
      {
        id: 1,
        stepNumber: 1,
        action: "재료 준비",
        description: "김치를 잘게 썰고 대파를 송송 썹니다.",
        ingredients: ["신김치 1컵", "대파 1대"],
        tools: ["도마", "칼"],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 2,
        stepNumber: 2,
        action: "김치 볶기",
        description: "팬에 기름을 두르고 김치를 볶습니다.",
        ingredients: ["식용유 1T", "설탕 0.5T"],
        tools: ["프라이팬"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
        tips: "김치를 충분히 볶아야 맛있어요!",
      },
      {
        id: 3,
        stepNumber: 3,
        action: "밥 넣고 볶기",
        description: "찬밥을 넣고 고루 섞으며 볶습니다.",
        ingredients: ["찬밥 2공기", "참기름 1T"],
        tools: ["뒤집개"],
        duration: 180,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
      {
        id: 4,
        stepNumber: 4,
        action: "완성",
        description: "계란 프라이를 올리고 김가루를 뿌려 완성합니다.",
        ingredients: ["계란 2개", "김가루"],
        tools: [],
        duration: 120,
        imageUrl: "/placeholder.svg?height=400&width=600",
      },
    ],
  },
]
